services:
  - type: web
    name: my-flask-app
    runtime: python
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
    dockerCommand: "./start.sh"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 server:app"
