services:
  - type: web
    name: celebrity-look-a-like
    env: docker
    image: anuragkatkar/facerecognitionserver  # <-- Your Docker Hub image
    plan: free
    autoDeploy: false  # Only deploy when you push a new image manually
